name: update ZDI Advisories
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
        pip install requests
        pip install lxml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: update db
      run: python3 ZDI_advisory_update.py

    - name: Commit
      run: |
        git config --global user.email delikely@gmail.com
        git config --global user.name delikely
        git add advisories
        git commit --allow-empty -m "update(`date +'%Y-%m-%d'`)"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ github.token }}
